import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="hyperinknue"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col p-4 min-h-full">
        <ul className="flex flex-row gap-2 p-4">
          <li className="bg-secondary-500 p-2 rounded-2xl">
            <Link className="p-2 font-bold" href="/input">
              Input
            </Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
