import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="hyperinknue"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col p-4 min-h-full">
        <div>
          <h1 className="font-bold text-2xl">HyperInk UI Playground</h1>
          <ul className="flex flex-row gap-2 p-2 pb-4">
            <li className="rounded text-secondary-500 hover:text-primary-400 text-lg hover:underline">
              <Link className="font-bold" href="/input">
                Input
              </Link>
            </li>
            <li className="rounded text-secondary-500 hover:text-primary-400 text-lg hover:underline">
              <Link className="font-bold" href="/input-check">
                Input Check
              </Link>
            </li>
            <li className="rounded text-secondary-500 hover:text-primary-400 text-lg hover:underline">
              <Link className="font-bold" href="/select">
                Select
              </Link>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
