packages:
  - "apps/*"
  - "apps/customer-sites/*"
  - "packages/consts"
  - "packages/api"
  - "packages/services"
  - "packages/business"
  - "packages/db"
  - "packages/hooks"
  - "packages/ui/*"
  - "packages/ui/*/*"
  - "packages/utils"
